---
- name: Add cloudflare-update-record.yml
  hosts: "cluster"
  tasks:
    - name: Get tools from GitHub
      ansible.builtin.git:
        repo: 'https://github.com/va1entin/tools'
        dest: /root/tools

    - name: Add config for DynDns renewal script
      copy:
        src: ../configs/cloudflare/cloudflare-config.yaml
        dest: /root/tools/cloudflare-update-record/cloudflare-update-record_config.yaml
        mode: '0600'

    - name: Add cron job for DynDns renewal
      cron:
        name: "Update DynDns at cloudflare"
        cron_file: "cloudflare-update-record"
        user: "root"
        minute: "0"
        hour: "*/4"
        job: "/root/tools/cloudflare-update-record/cloudflare-update-record.py -4"
