---
- name: Add cloudflare-update-record.yml
  hosts: "pis"
  tasks:
    - name: Get tools from GitHub
      ansible.builtin.git:
        repo: 'https://github.com/va1entin/tools'
        dest: /root/tools

    - name: Make sure pyyaml is installed
      ansible.builtin.pip:
        name: "pyyaml"
        state: present

    - name: Add config for DynDns renewal script
      copy:
        src: ../configs/cloudflare/cloudflare_config_{{ inventory_hostname }}.yaml
        dest: /root/tools/cloudflare_update_record/cloudflare_update_record_config.yaml
        mode: '0600'

    - name: Add cron job for DynDns renewal
      cron:
        name: "Update DynDns at cloudflare"
        cron_file: "cloudflare_update_record"
        user: "root"
        minute: "*/5"
        job: "cd /root/tools/cloudflare_update_record/; ./cloudflare_update_record.py -4"
