---
- name: HifiBerry & Bluetooth Audio fixes and customziations
  hosts: "pi4"
  tasks:
    - name: Wait for confirmation that rpi-audio-receiver scripts were run
      ansible.builtin.pause:
        prompt: "Please run the rpi-audio-receiver scripts before continuing: https://github.com/nicokaiser/rpi-audio-receiver/blob/a75cd56c8464a22c37ca4f215d6088a023565781 Press any key to continue or Ctrl+C to abort..."
        echo: no
    # for Hifiberry reference https://www.hifiberry.com/docs/software/configuring-linux-3-18-x/

    - name: Add noaudio to dtoverlay=vc4-kms-v3d to disable HDMI audio
      ansible.builtin.replace:
        path: /boot/config.txt
        regexp: '^dtoverlay=vc4-kms-v3d$'
        replace: 'dtoverlay=vc4-kms-v3d,noaudio'

    # Connect sounds

    - name: Print message about configuring connect sounds
      ansible.builtin.debug:
        msg: Going to add custom connect sounds. You must adapt the bluetooth-udev script for this to (maybe) work https://github.com/nicokaiser/rpi-audio-receiver/wiki/Bluetooth-connect-sounds

    - name: Ensure /usr/local/share/sounds/__custom dir exists
      ansible.builtin.file:
        path: /usr/local/share/sounds/__custom
        state: directory

    - name: Add device-added.wav
      ansible.builtin.copy:
        src: ../ignore/bluetooth/device-added.wav
        dest: /usr/local/share/sounds/__custom/device-added.wav

    - name: Add device-removed.wav
      ansible.builtin.copy:
        src: ../ignore/bluetooth/device-removed.wav
        dest: /usr/local/share/sounds/__custom/device-removed.wav

    - name: Print message about testing audio output
      ansible.builtin.debug:
        msg: Test audio output with `aplay /usr/local/share/sounds/__custom/device-added.wav`

    # - name: Reboot
    #  ansible.builtin.reboot:
