---
- name: Motioneye non-docker 32bit
# https://github.com/motioneye-project/motioneye?tab=readme-ov-file#installation
  hosts: "pis"
  vars:
    motioneye_version: "0.43.1b1"
  tasks:

    # might fail with OOM on older devices
    # dd if=/dev/zero of=/swapfile bs=1024 count=524288; chown root:root /swapfile; chmod 0600 /swapfile; mkswap /swapfile; swapon /swapfile
    - name: Install motioneye with pip
      ansible.builtin.pip:
        name: motioneye=={{ motioneye_version }}
        state: present
      environment:
        PIP_BREAK_SYSTEM_PACKAGES: 1

    - name: Run motioneye_init script
      ansible.builtin.shell: motioneye_init
      register: motioneye_init_output

    - debug:
        var: motioneye_init_output

    - name: Stop and disable motion service
      ansible.builtin.systemd:
        name: motion
        enabled: false
        state: stopped

    - name: Restart motioneye service
      ansible.builtin.systemd:
        name: motioneye
        state: restarted

    - name: Add drive cleanup script
      copy:
        src: ../scripts/motioneye/clean_drive.sh
        dest: /root/clean_drive.sh
        mode: '0700'

    - name: Add cron job for drive cleanup script
      cron:
        name: "Clean drive"
        cron_file: "clean_drive"
        user: "root"
        minute: "0"
        hour: "3"
        job: "/root/clean_drive.sh"
