---
- name: Nginx
  hosts: "pi4"
  vars:
    config_dir: /etc/nginx
    html_content_dir: "{{ config_dir }}/html"
    host_media_dir: /home/mediaserver
    container_content_dir: /media
    nginx_location: /mediavault/
    letsencrypt_config_dir: /etc/letsencrypt
    letsencrypt_challenge_dir: /var/www/challenges/
  vars_files:
    - secrets.yml
  tasks:
    - name: Ensure dirs exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
      - "{{ config_dir }}"
      - "{{ html_content_dir }}"
      - "{{ letsencrypt_config_dir }}"
      - "{{ letsencrypt_challenge_dir }}"

    - name: Add nginx config
      ansible.builtin.template:
        src: ../configs/nginx/nginx.conf.j2
        dest: "{{ config_dir }}/nginx.conf"

    - name: Get mime.types from GitHub
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/nginx/nginx/master/conf/mime.types
        dest: "{{ config_dir }}/mime.types"
        mode: "0664"

    - name: Add nginx index.html
      ansible.builtin.template:
        src: ../configs/nginx/html/index.html.j2
        dest: "{{ html_content_dir }}/index.html"

    - name: Get nginx-autoindex-theme from GitHub
      ansible.builtin.git:
        repo: 'https://github.com/va1entin/nginx-autoindex-theme'
        dest: "{{ html_content_dir }}/nginx-autoindex-theme"
        force: yes

    - name: Get acme_tiny from GitHub
      ansible.builtin.git:
        repo: 'https://github.com/diafygi/acme-tiny'
        dest: "/root/acme_tiny"
        force: yes
        version: 5.0.1

    - name: Add LetsEncrypt account key
      ansible.builtin.copy:
        src: ../configs/nginx/letsencrypt/account.key
        dest: "{{ letsencrypt_config_dir }}/account.key"

    - name: Add LetsEncrypt domain key
      ansible.builtin.copy:
        src: ../configs/nginx/letsencrypt/domain.key
        dest: "{{ letsencrypt_config_dir }}/domain.key"

    - name: Add LetsEncrypt csr
      ansible.builtin.copy:
        src: ../configs/nginx/letsencrypt/domain.csr
        dest: "{{ letsencrypt_config_dir }}/domain.csr"

    # - name: Get initial LE cert
    #   ansible.builtin.command: '/root/tools/letsencrypt_renewal.sh'

    # ansible-galaxy collection install community.docker
    # to generate htpasswd:
    # apt install -y apache2-utils && htpasswd -c /etc/nginx/.htpasswd user1
    - name: Run nginx container
      community.docker.docker_container:
        name: nginx
        image: va1entin/nginx-extended
        detach: true
        network_mode: host
        restart: true
        restart_policy: always
        pull: true
        volumes:
          - "{{ letsencrypt_config_dir }}:{{ letsencrypt_config_dir }}:ro"
          - "{{ letsencrypt_challenge_dir }}:{{ letsencrypt_challenge_dir }}:ro"
          - "{{ config_dir }}:{{ config_dir }}:ro"
          - "{{ html_content_dir }}:/usr/share/nginx/html:ro"
          - "{{ host_media_dir }}:{{ container_content_dir }}"
        env:
          TZ: "Europe/Berlin"
        state: started

    - name: Add cron job - certificate renewal
      cron:
        name: "LE renewal"
        cron_file: "le_renewal"
        user: "root"
        minute: "0"
        hour: "0"
        day: "1"
        job: '/root/tools/letsencrypt_renewal.sh'
