---
- name: Nginx
  hosts: "cluster"
  vars:
    config_dir: /etc/nginx
    content_dir: "{{ config_dir }}/html"
    host_media_dir: /home/mediaserver
    container_content_dir: /media
    nginx_location: /mediavault/
  tasks:
    - name: Install python-docker and yamllint
      ansible.builtin.apt:
        name: "python3-docker,yamllint"
        force_apt_get: true
        state: latest

    - name: Ensure {{ config_dir }} dir exists
      ansible.builtin.file:
        path: "{{ config_dir }}"
        state: directory

    - name: Ensure {{ content_dir }} dir exists
      ansible.builtin.file:
        path: "{{ content_dir }}"
        state: directory

    - name: Add nginx config
      ansible.builtin.template:
        src: ../configs/nginx/nginx.conf.j2
        dest: "{{ config_dir }}/nginx.conf"

    - name: Get mime.types from GitHub
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/nginx/nginx/master/conf/mime.types
        dest: "{{ config_dir }}/mime.types"
        mode: '0664'

    - name: Add nginx index.html
      ansible.builtin.template:
        src: ../configs/nginx/html/index.html.j2
        dest: "{{ content_dir }}/index.html"

    - name: Get nginx-autoindex-theme from GitHub
      ansible.builtin.git:
        repo: 'https://github.com/va1entin/nginx-autoindex-theme'
        dest: "{{ content_dir }}/nginx-autoindex-theme"

    # ansible-galaxy collection install community.docker
    - name: Run nginx container
      community.docker.docker_container:
        name: nginx
        image: nginx:stable
        detach: true
        network_mode: host
        restart: true
        restart_policy: always
        pull: true
        volumes:
          - "{{ config_dir }}:{{ config_dir }}:ro"
          - "{{ host_media_dir }}:{{ container_content_dir }}:ro"
        env:
          TZ: "Europe/Berlin"
        state: started
