---
- name: Add remount media drive systemd service and timer
  hosts: "pi4"
  tasks:
    - name: Create systemd service unit file
      ansible.builtin.template:
        src: ../configs/systemd/services/remount_media_drive.service.j2
        dest: "/etc/systemd/system/remount_media_drive.service"
      become: yes

    - name: Create systemd timer unit file
      ansible.builtin.template:
        src: ../configs/systemd/timers/remount_media_drive.timer.j2
        dest: "/etc/systemd/system/remount_media_drive.timer"
      become: yes

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true
      become: yes

    - name: Enable and start systemd timer
      ansible.builtin.systemd:
        name: remount_media_drive.timer
        enabled: true
        state: started
      become: yes